export const BRAND = {
  name: "Triple H Contracts & Hire",
  shortName: "Triple H",
  strapline: "Real work. Great people. Building tomorrow.",
  phone: "07939 306252",
  email: "amy.hewitt@triplehcontracts-hire.com",
  address: "West Yorkshire, United Kingdom",
};

export const MEDIA = {
  hero: "https://res.cloudinary.com/dr3bs0kcp/image/upload/v1789901049/triple-h/website/hero.png",
  arborist:
    "https://res.cloudinary.com/dr3bs0kcp/image/upload/v1789901051/triple-h/website/arborist.png",
  team: "https://res.cloudinary.com/dr3bs0kcp/image/upload/v1789901052/triple-h/website/team.png",
};

export const services = [
  {
    slug: "tree-surgery",
    title: "Tree Surgery",
    number: "01",
    excerpt:
      "Commercial arboriculture for complex sites, highways, waterways and hard-to-reach infrastructure.",
    image: MEDIA.arborist,
    highlights: [
      "Pruning, felling and crown management",
      "Rope access and traffic management integration",
      "Emergency response and site clearance",
    ],
  },
  {
    slug: "site-clearance",
    title: "Site Clearance",
    number: "02",
    excerpt:
      "Safe, programmed vegetation clearance with the right plant, RAMS and environmental controls.",
    image: MEDIA.hero,
    highlights: ["Vegetation and scrub clearance", "Specialist machinery", "Responsible waste handling"],
  },
  {
    slug: "rope-access",
    title: "Rope Access",
    number: "03",
    excerpt:
      "Qualified operatives and LOLER-tested equipment for work over water, unstable ground and structures.",
    image: MEDIA.arborist,
    highlights: ["Working at height", "Bridge and viaduct access", "Detailed risk assessment"],
  },
  {
    slug: "traffic-management",
    title: "Traffic Management",
    number: "04",
    excerpt:
      "Temporary traffic management, road closures, drawings and planning delivered by qualified teams.",
    image: MEDIA.team,
    highlights: ["Road closures and diversions", "CAD plans and paperwork", "Standalone or integrated delivery"],
  },
  {
    slug: "landscaping",
    title: "Landscaping",
    number: "05",
    excerpt:
      "Commercial soft landscaping, reinstatement and habitat-conscious planting for demanding sites.",
    image: MEDIA.team,
    highlights: ["Commercial landscaping", "Planting and reinstatement", "Planned maintenance"],
  },
  {
    slug: "invasive-weed-control",
    title: "Invasive Weed Control",
    number: "06",
    excerpt:
      "Assessment-led treatment programmes with controlled removal, records and licensed disposal routes.",
    image: MEDIA.arborist,
    highlights: ["Species assessment", "Treatment programmes", "Licensed handling and disposal"],
  },
  {
    slug: "grounds-maintenance",
    title: "Grounds Maintenance",
    number: "07",
    excerpt:
      "Recurring vegetation maintenance for highway, waterway and large commercial networks.",
    image: MEDIA.hero,
    highlights: ["Large-scale grass cutting", "Hedge and vegetation management", "Specialist flails and mowers"],
  },
  {
    slug: "emergency-call-out",
    title: "24/7 Emergency Call Out",
    number: "08",
    excerpt:
      "A direct response route for urgent tree, vegetation and access incidents, day or night.",
    image: MEDIA.hero,
    highlights: ["24-hour availability", "Rapid make-safe response", "Commercial and infrastructure sites"],
  },
];

export const projects = [
  {
    slug: "motorway-verge-recovery",
    title: "Motorway Verge Recovery",
    service: "Grounds Maintenance",
    sector: "Highways",
    location: "Yorkshire",
    excerpt: "A phased vegetation programme delivered around live carriageway constraints.",
    image: MEDIA.hero,
  },
  {
    slug: "bridge-rope-access-clearance",
    title: "Bridge Rope Access Clearance",
    service: "Rope Access",
    sector: "Infrastructure",
    location: "North of England",
    excerpt: "Specialist access planning for vegetation and debris clearance around a live structure.",
    image: MEDIA.arborist,
  },
  {
    slug: "commercial-site-enabling",
    title: "Commercial Site Enabling",
    service: "Site Clearance",
    sector: "Construction",
    location: "West Yorkshire",
    excerpt: "Coordinated clearance and traffic management ahead of a major construction programme.",
    image: MEDIA.team,
  },
];

export const news = [
  {
    slug: "inside-a-triple-h-delivery-day",
    title: "Inside the work: one team, one demanding delivery",
    date: "2026-09-18",
    category: "Projects",
    excerpt: "Go behind the barriers on a live highways shift where planning, specialist plant and straight-talking teamwork turned a difficult brief into a safe handback.",
    image: MEDIA.hero,
    seo: {
      title: "Inside a Triple H Highways Delivery Day",
      description: "See how Triple H plans and delivers a demanding live highways vegetation package with specialist people, plant and safety systems.",
      keywords: "highways vegetation management, commercial arboriculture, Triple H projects, roadside maintenance",
      ogTitle: "One shift. One team. A properly controlled delivery.",
      ogDescription: "Go behind the barriers with Triple H on a live highways vegetation shift.",
      ogImage: { secureUrl: MEDIA.hero, alt: "Triple H roadside machinery at work" },
      canonical: "/news/inside-a-triple-h-delivery-day",
      noIndex: false,
    },
    pageBuilderEnabled: true,
    blocks: [
      {
        id: "showcase-intro",
        type: "content",
        eyebrow: "Behind the work",
        title: "A tight window. A clear plan.",
        theme: "light",
        body: "<p>Before the first machine moved, the team had already worked through access, traffic management, ecology, emergency arrangements and the handback sequence. That preparation gave every person on shift a clear job and one shared standard.</p><p>This was more than a clearance package. It was a coordinated delivery around live infrastructure, changing ground conditions and a fixed reopening time.</p>",
      },
      {
        id: "showcase-stats",
        type: "stats",
        eyebrow: "The shift in numbers",
        title: "Measured from briefing to handback.",
        items: [
          { value: "14", label: "Skilled people on the night shift" },
          { value: "6.2km", label: "Of verge and vegetation managed" },
          { value: "0", label: "Safety incidents or missed controls" },
          { value: "43min", label: "Ahead of the handback deadline" },
        ],
      },
      {
        id: "showcase-feature-image",
        type: "image",
        image: { secureUrl: MEDIA.arborist, url: MEDIA.arborist, alt: "Triple H arborist completing specialist tree work" },
        caption: "Specialist access and clear communication kept the workface moving safely.",
        layout: "wide",
      },
      {
        id: "showcase-ticks",
        type: "ticks",
        eyebrow: "Built into the job",
        title: "Controls that work in the real world.",
        theme: "dark",
        items: [
          "A single, understood sequence for traffic management and plant movements",
          "Ecology checks completed before each new work area opened",
          "Supervisors positioned where decisions could be made quickly",
          "Live progress reporting shared with the client throughout the shift",
          "A clean, photographed and signed-off handback before reopening",
        ],
      },
      {
        id: "showcase-gallery",
        type: "gallery",
        eyebrow: "On the ground",
        title: "The shift, frame by frame.",
        autoplay: true,
        images: [
          { secureUrl: MEDIA.hero, url: MEDIA.hero, alt: "Triple H machinery working beside a live highway", caption: "The workface established and machinery moving through the first section." },
          { secureUrl: MEDIA.arborist, url: MEDIA.arborist, alt: "Qualified arborist working at height", caption: "Specialist arboriculture completed within the controlled zone." },
          { secureUrl: MEDIA.team, url: MEDIA.team, alt: "Triple H team preparing for work", caption: "The team briefing before the next work area opened." },
          { secureUrl: MEDIA.hero, url: MEDIA.hero, alt: "Roadside maintenance equipment during delivery", caption: "Final clearance, checks and evidence before handback." },
        ],
      },
      {
        id: "showcase-video",
        type: "video",
        video: null,
        poster: { secureUrl: MEDIA.hero, url: MEDIA.hero, alt: "Triple H roadside delivery video poster" },
        caption: "Add a project film from the site media library to bring the delivery story to life.",
        autoplay: false,
        controls: true,
        loop: false,
        muted: false,
        layout: "wide",
      },
      {
        id: "showcase-quote",
        type: "quote",
        quote: "Good delivery looks calm because the hard thinking happened before the shift began.",
        attribution: "Triple H Operations Team",
        theme: "red",
      },
      {
        id: "showcase-close",
        type: "content",
        eyebrow: "What made the difference",
        title: "People who own the outcome.",
        theme: "light",
        body: "<p>Plans matter, but delivery depends on people noticing the detail and speaking up early. The operatives, machine drivers, supervisors and traffic management crew worked as one team from mobilisation to demobilisation.</p><p>The result was a safer shift, a stronger finish and a client who knew exactly where the programme stood.</p>",
      },
      {
        id: "showcase-cta",
        type: "cta",
        eyebrow: "Need the same control?",
        title: "Bring us the difficult brief.",
        text: "Tell us what the site, programme and constraints look like. We’ll help shape a practical route to delivery.",
        link: { label: "Start a conversation", url: "/contact", newTab: false },
        theme: "dark",
      },
      {
        id: "showcase-enquiry",
        type: "enquiry",
        eyebrow: "Project enquiry",
        title: "Let’s get into the detail.",
        text: "Share the basics below and the right person from Triple H will come back to you.",
      },
    ],
  },
  {
    slug: "building-the-next-chapter",
    title: "Building the next chapter",
    date: "2026-09-12",
    category: "Company",
    excerpt: "Triple H is investing in people, plant and systems to support the next stage of growth.",
    image: MEDIA.team,
  },
  {
    slug: "new-roadside-maintenance-capability",
    title: "New roadside maintenance capability",
    date: "2026-08-28",
    category: "Fleet",
    excerpt: "A look at the equipment helping our teams deliver safer, more efficient vegetation work.",
    image: MEDIA.hero,
  },
  {
    slug: "careers-at-triple-h",
    title: "Real work. Real progression.",
    date: "2026-08-04",
    category: "People",
    excerpt: "Why we are building long-term careers for operatives across our expanding contracts.",
    image: MEDIA.team,
  },
  {
    slug: "night-shift-motorway-clearance-complete",
    title: "Night-shift motorway clearance completed ahead of programme",
    date: "2026-07-21",
    category: "Projects",
    excerpt: "Our highways team completed a tightly programmed clearance package across four overnight possessions.",
    image: MEDIA.hero,
  },
  {
    slug: "five-new-apprentices-join-the-team",
    title: "Five new apprentices join the Triple H team",
    date: "2026-07-08",
    category: "People",
    excerpt: "The new starters will build practical experience across arboriculture, plant and site operations.",
    image: MEDIA.team,
  },
  {
    slug: "summer-vegetation-programme-mobilises",
    title: "Summer vegetation programme mobilises across the North",
    date: "2026-06-19",
    category: "Projects",
    excerpt: "Crews, specialist machinery and traffic management resources are now deployed across the seasonal programme.",
    image: MEDIA.arborist,
  },
  {
    slug: "toolbox-talks-that-stick",
    title: "Toolbox talks that stick: making briefings count",
    date: "2026-06-03",
    category: "Safety",
    excerpt: "A practical look at how our supervisors keep daily safety conversations clear, relevant and useful.",
    image: MEDIA.team,
  },
  {
    slug: "new-remote-controlled-mower",
    title: "New remote-controlled mower strengthens steep-slope capability",
    date: "2026-05-14",
    category: "Fleet",
    excerpt: "The latest addition to our fleet improves productivity while keeping operatives away from higher-risk terrain.",
    image: MEDIA.hero,
  },
  {
    slug: "protecting-nesting-season",
    title: "Planning vegetation work around nesting season",
    date: "2026-04-27",
    category: "Environment",
    excerpt: "How surveys, exclusion zones and responsive programming help us protect wildlife while maintaining critical assets.",
    image: MEDIA.arborist,
  },
  {
    slug: "first-aid-training-day",
    title: "Operational teams complete advanced first-aid training",
    date: "2026-04-09",
    category: "Training",
    excerpt: "Field teams refreshed the practical skills needed to respond confidently in remote and roadside environments.",
    image: MEDIA.team,
  },
  {
    slug: "canal-corridor-clearance",
    title: "Canal corridor clearance opens up a critical inspection route",
    date: "2026-03-18",
    category: "Projects",
    excerpt: "Rope-access arborists and ground teams worked together to restore safe access along a constrained waterway.",
    image: MEDIA.arborist,
  },
  {
    slug: "women-in-arboriculture",
    title: "Backing the next generation of women in arboriculture",
    date: "2026-03-06",
    category: "People",
    excerpt: "Team members share their routes into the industry and why visible progression matters.",
    image: MEDIA.team,
  },
  {
    slug: "carbon-reporting-baseline",
    title: "Establishing a clearer carbon reporting baseline",
    date: "2026-02-20",
    category: "Environment",
    excerpt: "We are improving how fuel, journeys and disposal routes are recorded across live contracts.",
    image: MEDIA.hero,
  },
  {
    slug: "winter-response-review",
    title: "What we learned from this winter’s emergency response",
    date: "2026-02-04",
    category: "Company",
    excerpt: "A review of mobilisation times, communication and the equipment that kept urgent works moving.",
    image: MEDIA.hero,
  },
  {
    slug: "chainsaw-refresher-week",
    title: "Chainsaw refresher week sharpens core skills",
    date: "2026-01-16",
    category: "Training",
    excerpt: "Operatives revisited safe cutting techniques, maintenance checks and decision-making under pressure.",
    image: MEDIA.arborist,
  },
  {
    slug: "community-woodland-volunteer-day",
    title: "Triple H volunteers support community woodland day",
    date: "2025-12-11",
    category: "Community",
    excerpt: "Colleagues donated time, tools and practical knowledge to improve paths and habitats at a local woodland.",
    image: MEDIA.team,
  },
  {
    slug: "fleet-winter-readiness",
    title: "Fleet workshop completes winter-readiness programme",
    date: "2025-11-24",
    category: "Fleet",
    excerpt: "Preventative maintenance and cold-weather checks have been completed across core machinery and support vehicles.",
    image: MEDIA.hero,
  },
  {
    slug: "near-miss-learning-workshop",
    title: "Near-miss workshop turns reporting into practical learning",
    date: "2025-10-17",
    category: "Safety",
    excerpt: "Supervisors worked through real scenarios to identify stronger controls and share lessons across contracts.",
    image: MEDIA.team,
  },
  {
    slug: "rail-embankment-package-awarded",
    title: "Triple H awarded regional rail embankment package",
    date: "2025-09-29",
    category: "Company",
    excerpt: "The multi-site programme brings together vegetation management, access planning and environmental controls.",
    image: MEDIA.arborist,
  },
  {
    slug: "habitat-piles-from-arisings",
    title: "Turning site arisings into habitat piles",
    date: "2025-08-12",
    category: "Environment",
    excerpt: "A simple change in processing is helping suitable sites retain more ecological value after clearance works.",
    image: MEDIA.arborist,
  },
  {
    slug: "supervisor-development-programme",
    title: "Supervisor development programme reaches first milestone",
    date: "2025-07-25",
    category: "Training",
    excerpt: "The first cohort has completed modules covering planning, leadership, quality and client communication.",
    image: MEDIA.team,
  },
  {
    slug: "school-careers-demonstration",
    title: "Local students get a closer look at land-based careers",
    date: "2025-06-13",
    category: "Community",
    excerpt: "Our team delivered a machinery and arboriculture demonstration for students exploring practical careers.",
    image: MEDIA.hero,
  },
  {
    slug: "bridge-inspection-enabling-works",
    title: "Bridge inspection enabling works delivered without closure overrun",
    date: "2025-05-22",
    category: "Projects",
    excerpt: "Detailed access planning helped the team clear inspection zones and hand the structure back on time.",
    image: MEDIA.arborist,
  },
];

export const vacancies = [
  {
    slug: "general-operative",
    title: "General Operative",
    location: "Yorkshire / Nationwide",
    salary: "Competitive",
    hours: "Full time",
    category: "Operations",
    excerpt: "Join a practical, safety-led team working across infrastructure and commercial sites.",
  },
  {
    slug: "machine-operative",
    title: "Machine Operative",
    location: "Yorkshire / Nationwide",
    salary: "Competitive, dependent on tickets",
    hours: "Full time",
    category: "Plant",
    excerpt: "Operate specialist machinery across vegetation, clearance and highway contracts.",
  },
  {
    slug: "arborist",
    title: "Arborist",
    location: "Nationwide contracts",
    salary: "Competitive, dependent on experience",
    hours: "Full time",
    category: "Arboriculture",
    excerpt: "Bring your climbing, cutting and team skills to varied commercial arboriculture work.",
  },
  {
    slug: "contracts-supervisor",
    title: "Contracts Supervisor",
    location: "West Yorkshire",
    salary: "Competitive",
    hours: "Full time",
    category: "Management",
    excerpt: "Lead safe, well-planned delivery and help good people do their best work.",
  },
];

export const teamMembers = [
  {
    slug: "amy-hewitt",
    title: "Amy Hewitt",
    category: "Managing Director",
    excerpt: "Amy leads the business with a focus on dependable delivery, strong client relationships and long-term opportunities for the team.",
    body: "<p>Amy keeps Triple H moving in the right direction, bringing commercial clarity and a people-first approach to every contract.</p><p>She works closely with clients, supervisors and delivery teams to make sure promises made at tender stage are carried through on site.</p>",
    image: MEDIA.team,
  },
  {
    slug: "freya-ward",
    title: "Freya Ward",
    category: "Contracts Manager",
    excerpt: "Freya turns complex programmes into clear, safe and well-coordinated delivery plans.",
    body: "<p>Freya oversees contract mobilisation, programming and client reporting across the business.</p><p>Her practical approach helps teams anticipate challenges early and keep quality, safety and communication aligned.</p>",
    image: MEDIA.arborist,
  },
  {
    slug: "aaron-cole",
    title: "Aaron Cole",
    category: "Operations Supervisor",
    excerpt: "Aaron supports field teams and keeps daily delivery safe, efficient and accountable.",
    body: "<p>Aaron coordinates operatives, plant and site requirements across fast-moving contracts.</p><p>He is known for calm decision-making, straight communication and an eye for the details that keep work progressing.</p>",
    image: MEDIA.hero,
  },
  {
    slug: "beth-morgan",
    title: "Beth Morgan",
    category: "Lead Arborist",
    excerpt: "Beth brings technical arboriculture knowledge and confident leadership to challenging sites.",
    body: "<p>Beth leads climbing and tree-work operations, helping teams select safe methods for difficult access and sensitive environments.</p><p>She also supports mentoring and skills development across the arboriculture team.</p>",
    image: MEDIA.arborist,
  },
  {
    slug: "callum-shaw",
    title: "Callum Shaw",
    category: "Plant & Fleet Lead",
    excerpt: "Callum makes sure the right machines, checks and maintenance are in place for every job.",
    body: "<p>Callum manages specialist plant readiness and works with supervisors to match equipment to each site.</p><p>His focus on planning and preventative maintenance helps reduce downtime and improve productivity.</p>",
    image: MEDIA.hero,
  },
  {
    slug: "demi-khan",
    title: "Demi Khan",
    category: "Traffic Management Coordinator",
    excerpt: "Demi connects planning, permits and site delivery so teams can work safely around live roads.",
    body: "<p>Demi coordinates temporary traffic management requirements, drawings and delivery partners.</p><p>She keeps clients informed and makes sure site teams have the information they need before work begins.</p>",
    image: MEDIA.team,
  },
];

export const testimonials = [
  {
    slug: "northline-infrastructure",
    title: "Alex Turner",
    category: "Northline Infrastructure",
    excerpt: "Triple H brought a proper delivery mindset from day one. The team communicated clearly, adapted quickly and left the site exactly as promised.",
    body: "<p>Their supervisors understood the operational pressure around the programme and made difficult work feel controlled.</p>",
  },
  {
    slug: "civicworks-partnership",
    title: "Priya Singh",
    category: "CivicWorks Partnership",
    excerpt: "Professional, responsive and easy to work with. The standard of planning was just as strong as the work on site.",
    body: "<p>We always knew what was happening, who was responsible and what the next milestone looked like.</p>",
  },
  {
    slug: "buildright-developments",
    title: "Dan Hughes",
    category: "BuildRight Developments",
    excerpt: "The Triple H team handled a demanding clearance package safely and kept our wider construction programme moving.",
    body: "<p>Their plant capability and practical problem-solving made a noticeable difference.</p>",
  },
  {
    slug: "waterways-north",
    title: "Maya Foster",
    category: "Waterways North",
    excerpt: "A confident team who understood the environmental sensitivities of the site and worked around them carefully.",
    body: "<p>Communication with our stakeholders was excellent throughout the project.</p>",
  },
  {
    slug: "unified-facilities",
    title: "Tom Beck",
    category: "Unified Facilities",
    excerpt: "Reliable attendance, tidy delivery and no drama. Triple H has become a trusted extension of our own team.",
    body: "<p>They are proactive about raising issues early and always arrive with a workable solution.</p>",
  },
  {
    slug: "landholdings-group",
    title: "Leah Owen",
    category: "Landholdings Group",
    excerpt: "From the first survey through to completion, the process was organised, transparent and refreshingly straightforward.",
    body: "<p>The finish was excellent and the team treated the surrounding site with real care.</p>",
  },
  {
    slug: "northern-route-partners",
    title: "Marcus Reed",
    category: "Northern Route Partners",
    excerpt: "Triple H stepped into a live highways programme and immediately gave us confidence. Their supervisors were visible, the paperwork was clear and every shift finished with an honest update.",
    body: "<p>When access changed at short notice, the team reorganised plant and labour without losing the possession. That level of calm, practical delivery is exactly what we need from a specialist contractor.</p>",
  },
  {
    slug: "greenbank-estates",
    title: "Sophie Grant",
    category: "Greenbank Estates",
    excerpt: "The difference was in the preparation. Triple H understood the site constraints, protected the areas that mattered and delivered a large clearance package without disrupting our tenants.",
    body: "<p>The daily communication was concise and useful, and the site was handed back clean, secure and ready for the next phase of work.</p>",
  },
  {
    slug: "westmoor-civils",
    title: "Jordan Ellis",
    category: "Westmoor Civils",
    excerpt: "A dependable delivery partner from survey through to sign-off. The team combined the right machinery with experienced operators and never lost sight of safety or programme pressure.",
    body: "<p>They raised potential issues early, arrived with solutions and worked well alongside our own crews. We would have no hesitation bringing them onto another complex package.</p>",
  },
  {
    slug: "pennine-utilities",
    title: "Rachel King",
    category: "Pennine Utilities",
    excerpt: "We needed vegetation clearance around sensitive infrastructure with tight access and a demanding sequence. Triple H planned it properly and delivered exactly what had been agreed.",
    body: "<p>The operatives were professional with our stakeholders, the reporting was consistent and the finished work gave our next contractor a clear, safe start.</p>",
  },
  {
    slug: "metroline-projects",
    title: "Owen Price",
    category: "Metroline Projects",
    excerpt: "Their traffic management and arboriculture teams worked as one joined-up operation. That coordination removed delays and made a difficult roadside package feel straightforward.",
    body: "<p>Every change was communicated before it became a problem, and the supervisor remained available throughout. It was a strong performance from start to finish.</p>",
  },
  {
    slug: "heritage-water-services",
    title: "Nadia Clarke",
    category: "Heritage Water Services",
    excerpt: "Triple H treated a sensitive waterside site with the care it required. Their method balanced access, environmental protection and productivity without compromising any of them.",
    body: "<p>The crew was respectful, well briefed and clearly proud of the standard they left behind. Our environmental adviser was particularly impressed by the housekeeping and controls.</p>",
  },
  {
    slug: "summit-property-care",
    title: "Ben Walker",
    category: "Summit Property Care",
    excerpt: "We use Triple H because they are responsive without being rushed. They ask the right questions, commit to a sensible plan and then keep us informed until the work is complete.",
    body: "<p>That reliability matters across a busy estate where access and tenant communication can change quickly. Their team consistently represents us well on site.</p>",
  },
  {
    slug: "eastfield-construction",
    title: "Hannah Cole",
    category: "Eastfield Construction",
    excerpt: "The clearance phase was completed safely, ahead of programme and to a genuinely high finish. Triple H coordinated closely with our site manager and adapted around other trades.",
    body: "<p>Their plant selection saved time in the most restricted areas, while the ground team maintained excellent control of the work zone throughout.</p>",
  },
  {
    slug: "county-environmental",
    title: "Imran Shah",
    category: "County Environmental",
    excerpt: "A technically capable team with a refreshingly direct style of communication. They understood the ecological controls and made sure every operative knew what was expected.",
    body: "<p>The records were complete, the toolbox talks were relevant and the site checks matched what had been promised in the method statement.</p>",
  },
  {
    slug: "ridgeway-highways",
    title: "Lucy Bennett",
    category: "Ridgeway Highways",
    excerpt: "From emergency call-out to final clearance, Triple H gave us a fast and controlled response. They mobilised safely, kept the carriageway team updated and removed the hazard efficiently.",
    body: "<p>The follow-up information arrived promptly and the area was left tidy. It is reassuring to have a contractor who can respond at pace without lowering standards.</p>",
  },
  {
    slug: "oakbridge-housing",
    title: "Chris Morgan",
    category: "Oakbridge Housing",
    excerpt: "The team worked around residents with patience and professionalism. Their programme was realistic, notices were clear and the work areas were kept secure at every stage.",
    body: "<p>We received positive feedback from residents, which is not always easy on a noisy external works package. The completed landscaping has transformed the site.</p>",
  },
  {
    slug: "central-rail-assets",
    title: "Aisha Patel",
    category: "Central Rail Assets",
    excerpt: "Triple H brought strong planning discipline to a difficult access package. The team understood the importance of permits, interfaces and leaving nothing unresolved at shift handback.",
    body: "<p>Their briefings were sharp, supervision was consistent and productivity remained high even when the working window changed.</p>",
  },
  {
    slug: "landmark-development-group",
    title: "Peter Walsh",
    category: "Landmark Development Group",
    excerpt: "We asked for a contractor who could take ownership of the whole package, not simply provide labour. Triple H did exactly that and made our project team’s job considerably easier.",
    body: "<p>They coordinated surveys, machinery, disposal and reporting under one clear point of contact. The result was safe, efficient and commercially transparent.</p>",
  },
  {
    slug: "valley-parks-trust",
    title: "Emily Roberts",
    category: "Valley Parks Trust",
    excerpt: "The operatives combined technical skill with real consideration for a busy public space. They protected access routes, answered questions politely and maintained an immaculate work area.",
    body: "<p>The completed tree work looks excellent and the whole process was handled with care. We have already discussed the next phase with their team.</p>",
  },
];

export const aboutPages = [
  {
    slug: "our-story",
    title: "Our story",
    category: "About Triple H",
    excerpt: "A practical business built around capable people, honest relationships and a determination to keep raising the standard.",
    body: "<h2>Built from the ground up.</h2><p>Triple H Contracts & Hire grew from a simple belief: demanding outdoor work deserves better planning, better communication and a team that takes real pride in the finish.</p><p>Today, we bring together skilled operatives, supervisors, specialist plant and trusted partners to support infrastructure and commercial clients across the UK.</p><h2>Ready for the next challenge.</h2><p>We continue to invest in people, machinery and systems so we can take on more complex projects without losing the responsive, personal service that shaped the business.</p>",
    image: MEDIA.team,
  },
  {
    slug: "values",
    title: "Our values & standards",
    category: "How we work",
    excerpt: "Safety, quality, teamwork and progression are the standards behind every decision we make.",
    body: "<h2>Safety comes first.</h2><p>We plan thoroughly, speak up early and make sure everyone understands the method before work begins.</p><h2>Quality is owned.</h2><p>Every member of the team is responsible for the finish, the details and the client experience.</p><h2>Teamwork gets it done.</h2><p>We share knowledge, communicate without ego and back each other when conditions change.</p><h2>Progression keeps us moving.</h2><p>We invest in training, better equipment and smarter systems that create stronger careers and better outcomes.</p>",
    image: MEDIA.hero,
  },
];

export const collectionDefaults = {
  service: services,
  project: projects,
  news,
  vacancy: vacancies,
  "team-member": teamMembers,
  testimonial: testimonials,
  page: aboutPages,
};

export const employeeSeed = [
  ["Aaron Cole", "aaron.cole@tripleh-demo.test", "Operations"],
  ["Beth Morgan", "beth.morgan@tripleh-demo.test", "Arboriculture"],
  ["Callum Shaw", "callum.shaw@tripleh-demo.test", "Plant"],
  ["Demi Khan", "demi.khan@tripleh-demo.test", "Traffic Management"],
  ["Elliot Price", "elliot.price@tripleh-demo.test", "Operations"],
  ["Freya Ward", "freya.ward@tripleh-demo.test", "Management"],
];

export const customerSeed = [
  ["Alex Turner", "alex@northline-demo.test", "Highways"],
  ["Priya Singh", "priya@civicworks-demo.test", "Public Sector"],
  ["Dan Hughes", "dan@buildright-demo.test", "Construction"],
  ["Maya Foster", "maya@waterways-demo.test", "Waterways"],
  ["Tom Beck", "tom@facilities-demo.test", "Facilities"],
  ["Leah Owen", "leah@landholdings-demo.test", "Land Management"],
];
